### ISSUE TITLE
problems installing

### ISSUE THREAD

**Issue by jthDEV** [TrustSource/ts-scan#11]
I tried to install using 'pip install ts-scan' under Python 3.12 and installation fails due to old/problematic version of Numpy.
Then I create a new virtual pyenv under 3.10.5 and ran the same command. This time it succeeded with 

```
Successfully built grapheme semanticversion progress
Installing collected packages: text-unidecode, semanticversion, progress, osadl-matrix, grapheme, cymem, zipp, wasabi, urllib3, typing-extensions, tqdm, tomli, spacy-loggers, spacy-legacy, smart-open, six, regex, pyproject_hooks, pyminr, pathlib-abc, packaging, numpy, murmurhash, MarkupSafe, marisa-trie, joblib, idna, defusedxml, click, charset-normalizer, certifi, catalogue, about-time, typer, srsly, requests, pydantic, preshed, nltk, language-data, jinja2, importlib-metadata, build, blis, alive-progress, ts-python-client, pathy, langcodes, confection, thinc, spacy, ts-deepscan, ts-scan
Successfully installed MarkupSafe-3.0.2 about-time-4.2.1 alive-progress-3.2.0 blis-0.7.11 build-1.2.2.post1 catalogue-2.0.10 certifi-2024.8.30 charset-normalizer-3.4.0 click-8.1.3 confection-0.1.5 cymem-2.0.8 defusedxml-0.7.1 grapheme-0.6.0 idna-3.10 importlib-metadata-8.5.0 jinja2-3.1.4 joblib-1.4.2 langcodes-3.4.1 language-data-1.2.0 marisa-trie-1.2.1 murmurhash-1.0.10 nltk-3.9.1 numpy-2.1.2 osadl-matrix-2024.5.22.10535 packaging-24.1 pathlib-abc-0.1.1 pathy-0.11.0 preshed-3.0.9 progress-1.6 pydantic-1.10.18 pyminr-0.1.1 pyproject_hooks-1.2.0 regex-2024.9.11 requests-2.32.3 semanticversion-0.1.7 six-1.16.0 smart-open-6.4.0 spacy-3.6.0 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.4.8 text-unidecode-1.3 thinc-8.1.12 tomli-2.0.2 tqdm-4.66.6 ts-deepscan-2.0.6 ts-python-client-2.0.4 ts-scan-0.2.2 typer-0.9.4 typing-extensions-4.12.2 urllib3-2.2.3 wasabi-1.1.3 zipp-3.20.2
WARNING: You are using pip version 22.0.4; however, version 24.3.1 is available.
You should consider upgrading via the '/Users/(...)/.pyenv/versions/3.10.5/envs/vulndb-api/bin/python -m pip install --upgrade pip' command.

```

But executing 'ts-scan --help' results in: 
```
Traceback (most recent call last):
  File "ts-scan", line 2, in <module>
    from ts_scan.cli import main
  File "/Users/janthielscher/dev/ts-scan/ts_scan/__init__.py", line 10, in <module>
    from ts_python_client.commands import parse_cmd_opts_from_args
ModuleNotFoundError: No module named 'ts_python_client.commands'
``

**Comment by gr-markin** [comment]
Fixed
